support older mill 0.10.x 0.11.y patch versions
joan38/mill-scalafix pull request #166
Opened 2023-11-06 12:08 UTC by IdiosApps

- [Example of safer millVersions](https://github.com/alexarchambault/mill-native-image/blob/master/build.sc#L8)
    - ["Mill does not guarantee any forward binary compatibilities"](https://github.com/alexarchambault/mill-native-image/pull/70/files#r1367870330)  
    - The [comment disables Steward bumps](https://github.com/alexarchambault/mill-native-image/commit/37575064e06c353255f157309cb76cad206da7b1)

@lefou could you sanity check this is a good suggestion? 😅

2023-11-06 13:20 UTC, lefou approved these changes
Looks good to me.

2023-11-06 13:55 UTC, IdiosApps commented
@joan38 WDYT? 

Also, should this be updated to some mill 0.11.x version? https://github.com/joan38/mill-scalafix/blob/main/.mill-version

2023-11-06 16:20 UTC, joan38 commented
@IdiosApps looks good.
For the miss version of this project we are stuck on 0.10 versions until BSP is repaired in 0.11

2023-11-07 20:31 UTC, joan38 commented
@IdiosApps Could you fix the compilation?

Also could you explain the motivation for supporting older patch versions?

2023-11-07 20:34 UTC, IdiosApps commented
> @IdiosApps Could you fix the compilation?
> 
> Also could you explain the motivation for supporting older patch versions?

I can try and fix it another day, sure.

Like I said, I don't fully understand, but trying to copy the pattern I'm seeing 😅 @lefou could you explain it a bit?

2023-11-07 20:39 UTC, joan38 commented
I understand mill is not forward compatible and therefore plugins need to be depending on older versions of mill than the end project is using. But why can't the end project upgrade the patch version? That is what I'm trying to understand.

Also [the example you linked](https://github.com/alexarchambault/mill-native-image/blob/master/build.sc#L8) seem to depend on 0.10.12

2023-11-07 20:42 UTC, lefou commented
There are always reasons to not use the latest versions. (The OP just provided an example: using an older version because a newer minor version introduces an issue and nobody else saw it so far.) If it does not hurt, why should one want to limit the compatibility of a plugin to only the latest version?

2023-11-07 20:47 UTC, lefou commented
And regarding this PR, we can't lower back to `0.10.0`, as the `semanticDbData` target was only introduced in Mill `0.10.6`, I think.

2023-11-07 21:37 UTC, lefou requested changes

2023-11-07 21:37 UTC, lefou commented on build.sc
> +val millVersions                           = Seq("0.10.0", "0.11.0") // scala-steward:off
I think, we need at least Mill 0.10.6, as this version introduces the `semanticDbData` target which this plugins relies on.

```suggestion
val millVersions                           = Seq("0.10.6", "0.11.0") // scala-steward:off
```

2023-11-08 11:03 UTC, lolgab commented
I think Mill 0.10 is now a "legacy" version of Mill, and I would be okay supporting only its latest version (`0.10.12`). Bumping to the latest patch version it's a no-brainer since they are backward compatible.
Also Mill `0.11.1` was released as a bug-fix release for `0.11.0` so I don't see point on supporting `0.11.0`

2023-11-08 12:16 UTC, lefou commented
> I think Mill 0.10 is now a "legacy" version of Mill, and I would be okay supporting only its latest version (`0.10.12`). Bumping to the latest patch version it's a no-brainer since they are backward compatible. Also Mill `0.11.1` was released as a bug-fix release for `0.11.0` so I don't see point on supporting `0.11.0`

This sounds reasonable. Yet, I'd like to ask *why* one should want to explicitly unsupport a certain version without any needs? We're talking about API here, not implementation. If the user runs with a newer version, e.g. to get all the upstream fixes and improvements, the plugin will use that newer version too.

From a users perspective, there is no easy way to detect, whether a plugin was build against a compatible API, besides the binary platform version. When analyzing build issues, this kind of incompatibility is less obvious and may lead to obscure error messages. And, tbh, this is against any best practice in plugin development for any kind of system I ever worked with.

2023-11-16 07:38 UTC, lefou commented
I just want to bring to your awareness, that there is a `mill-dependency-check` plugin that depends on this plugin, so using a proper (low) API baseline is even more important. 

I also found the following line in its `build.sc`, which _could_ be a good indicator for the kind of issues we _might_ produce if we do not care about compatibility.

https://github.com/Eleven19/mill-dependency-check/blob/fc4c8222faaf7b072c43a1a73b75102f04214c86/build.sc#L17

> ```
> // TODO Should probably drop this to 0.10.0, but when I did a bunch of stuff breaks
> val millVersion = "0.10.3"
> ```

2024-01-07 21:38 UTC, lefou commented
Mostly superseded by #172, which raised the lowest supported Mill version to 0.10.15. Maybe, the `scala-steward:off` comment is worth to add.

2024-01-07 22:40 UTC, joan38 commented
Good point !

2024-05-16 14:38 UTC, closed without merging

2024-05-16 14:38 UTC, joan38 commented
Closing this one. Reopen if needed